import type { TeamCode } from '../types';

/**
 * Canonical URL slug per team — the one slug that actually has its own
 * static HTML page (with team-specific title + OG meta) generated by
 * scripts/build-team-pages.mjs.
 *
 * MUST stay in sync with the slug list in build-team-pages.mjs. Other
 * variants live in src/state/teamSlugs.ts (alias map for the URL router)
 * and resolve to the same team via SPA routing, but they don't get
 * dedicated HTML pages with custom OG meta.
 */
export const CANONICAL_SLUG: Record<TeamCode, string> = {
  // Group A
  MEX: 'mexico',     RSA: 'south-africa', KOR: 'south-korea', CZE: 'czechia',
  // Group B
  CAN: 'canada',     BIH: 'bosnia',       QAT: 'qatar',       SUI: 'switzerland',
  // Group C
  BRA: 'brazil',     MAR: 'morocco',      HTI: 'haiti',       SCO: 'scotland',
  // Group D
  USA: 'united-states', PAR: 'paraguay',  AUS: 'australia',   TUR: 'turkiye',
  // Group E
  GER: 'germany',    CUW: 'curacao',      CIV: 'cote-divoire', ECU: 'ecuador',
  // Group F
  NED: 'netherlands', JPN: 'japan',       SWE: 'sweden',      TUN: 'tunisia',
  // Group G
  BEL: 'belgium',    EGY: 'egypt',        IRN: 'iran',        NZL: 'new-zealand',
  // Group H
  ESP: 'spain',      CPV: 'cape-verde',   KSA: 'saudi-arabia', URU: 'uruguay',
  // Group I
  FRA: 'france',     SEN: 'senegal',      IRQ: 'iraq',        NOR: 'norway',
  // Group J
  ARG: 'argentina',  ALG: 'algeria',      AUT: 'austria',     JOR: 'jordan',
  // Group K
  POR: 'portugal',   COD: 'dr-congo',     UZB: 'uzbekistan',  COL: 'colombia',
  // Group L
  ENG: 'england',    CRO: 'croatia',      GHA: 'ghana',       PAN: 'panama',
};
